parameters:
    ezpublish.fieldType.smilecampaign.converter.class: Smile\EzUICampaignBundle\Persistence\Content\FieldValue\Converter\CampaignConverter

services:
    ezpublish.fieldType.smilecampaign.converter:
        class: "%ezpublish.fieldType.smilecampaign.converter.class%"
        tags:
            - {name: ezpublish.storageEngine.legacy.converter, alias: smilecampaign, lazy: true, callback: '::create'}

