parameters:
    ezpublish.fieldType.smilecampaign.class: Smile\EzUICampaignBundle\FieldType\Campaign\Type
    ezrepoforms.field_type.form_mapper.smilecampaign.class: Smile\EzUICampaignBundle\FieldType\Campaign\FormMapper

services:
    ezpublish.fieldType.smilecampaign:
        class: "%ezpublish.fieldType.smilecampaign.class%"
        parent: ezpublish.fieldType
        tags:
            - {name: ezpublish.fieldType, alias: smilecampaign}

    ezrepoforms.field_type.form_mapper.smilecampaign:
        class: "%ezrepoforms.field_type.form_mapper.smilecampaign.class%"
        tags:
            - { name: ez.fieldFormMapper.definition, fieldType: smilecampaign }
            - { name: ez.fieldFormMapper.value, fieldType: smilecampaign }
        arguments:
            - "@ezpublish.api.service.field_type"

