parameters:
    ezpublish.fieldType.indexable.smilecampaign.class: Smile\EzUICampaignBundle\FieldType\Campaign\SearchField

services:
    ezpublish.fieldType.indexable.smilecampaign:
        class: "%ezpublish.fieldType.indexable.smilecampaign.class%"
        tags:
            - {name: ezpublish.fieldType.indexable, alias: smilecampaign}
