smileezcampaign_campaign:
    path: /campaign/{tabItem}/tab
    defaults: { _controller: smile.campaign.controller.campaign:campaignAction, tabItem: "campaigns" }
    requirements:
        tabItem: "[a-z]+"

smileezcampaign_campaign_view:
    path: /campaign/campaign/{id}/{mode}
    defaults: { _controller: smile.campaign.controller.campaign:viewAction, mode: false }
    requirements:
        id: "[0-9a-z]+"

smileezcampaign_campaign_edit:
    path: /campaign/campaign/edit/{id}
    defaults: { _controller: smile.campaign.controller.campaign:editAction, id: ~ }

smileezcampaign_folder_edit:
    path: /campaign/folder/edit/{id}
    defaults: { _controller: smile.campaign.controller.campaign:editFolderAction, id: ~ }

smileezcampaign_campaigns_new:
    path: /campaign/campaign/new
    defaults: { _controller: smile.campaign.controller.campaigns:newAction }

smileezcampaign_campaign_subscribe:
    path: /campaign/campaign/{id}/subscribe
    defaults: { _controller: smile.campaign.controller.campaign:subscribeAction }
    requirements:
        id: "[0-9a-z]+"

smileezcampaign_campaign_folders_new:
    path: /campaign/campaign/folder/new
    defaults: { _controller: smile.campaign.controller.campaigns:folderNewAction }

smileezcampaign_list_view:
    path: /campaign/list/{id}
    defaults: { _controller: smile.campaign.controller.list:viewAction }
    requirements:
        id: "[0-9a-z]+"

smileezcampaign_list_edit:
    path: /campaign/list/edit/{id}
    defaults: { _controller: smile.campaign.controller.list:editAction, id: ~ }

smileezcampaign_lists_new:
    path: /campaign/list/new
    defaults: { _controller: smile.campaign.controller.lists:newAction }

smileezcampaign_lists_folder_new:
    path: /campaign/list/folder/new
    defaults: { _controller: smile.campaign.controller.lists:folderNewAction }
