smileezcampaign_campaign:
    path: /campaign/{tabItem}/tab
    defaults: { _controller: smile.campaign.controller.campaign:campaignAction, tabItem: "campaigns" }
    requirements:
        tabItem: "[a-z]+"

smileezcampaign_campaign_view:
    path: /campaign/campaign/view/{campaignID}/{mode}
    defaults: { _controller: smile.campaign.controller.campaign:viewAction, mode: false }
    requirements:
        campaignID: "[0-9a-z]+"

smileezcampaign_campaign_edit:
    path: /campaign/campaign/edit/{campaignID}
    defaults: { _controller: smile.campaign.controller.campaign:editAction, campaignID: ~ }

smileezcampaign_campaign_delete:
    path: /campaign/list/delete/{campaignID}
    defaults: { _controller: smile.campaign.controller.campaign:deleteAction }
    requirements:
        campaignID: "[0-9a-z]+"

smileezcampaign_campaign_subscribe:
    path: /campaign/campaign/{campaignID}/subscribe
    defaults: { _controller: smile.campaign.controller.campaign:subscribeAction }
    requirements:
        campaignID: "[0-9a-z]+"

smileezcampaign_folder_edit:
    path: /campaign/folder/edit/{id}
    defaults: { _controller: smile.campaign.controller.campaign:editFolderAction, id: ~ }

smileezcampaign_list_view:
    path: /campaign/list/view/{campaignListID}
    defaults: { _controller: smile.campaign.controller.list:viewAction }
    requirements:
        campaignListID: "[0-9a-z]+"

smileezcampaign_list_edit:
    path: /campaign/list/edit/{campaignListID}
    defaults: { _controller: smile.campaign.controller.list:editAction, campaignListID: ~ }

smileezcampaign_list_delete:
    path: /campaign/list/delete/{campaignListID}
    defaults: { _controller: smile.campaign.controller.list:deleteAction }
    requirements:
        campaignListID: "[0-9a-z]+"

