parameters:
    smile.campaign.service.campaign.class: Smile\EzUICampaignBundle\Service\CampaignService
    smile.campaign.service.campaign_folders.class: Smile\EzUICampaignBundle\Service\CampaignFoldersService
    smile.campaign.service.campaign_folder.class: Smile\EzUICampaignBundle\Service\CampaignFolderService
    smile.campaign.service.campaigns.class: Smile\EzUICampaignBundle\Service\CampaignsService
    smile.campaign.service.list.class: Smile\EzUICampaignBundle\Service\ListService
    smile.campaign.service.lists.class: Smile\EzUICampaignBundle\Service\ListsService

    smile.campaign.controller.campaign.class: Smile\EzUICampaignBundle\Controller\CampaignController
    smile.campaign.controller.list.class: Smile\EzUICampaignBundle\Controller\ListController
    smile.campaign.controller.campaigns.class: Smile\EzUICampaignBundle\Controller\CampaignsController
    smile.campaign.controller.lists.class: Smile\EzUICampaignBundle\Controller\ListsController

    smile.campaign.tabs: [campaigns, lists]

services:
    # Services
    smile.campaign.service.campaign:
        class: %smile.campaign.service.campaign.class%
        arguments:
            - @welp_mailchimp.mailchimp_master
            - @smile.campaign.service.list

    smile.campaign.service.campaign_folders:
        class: %smile.campaign.service.campaign_folders.class%
        arguments:
            - @welp_mailchimp.mailchimp_master

    smile.campaign.service.campaign_folder:
        class: %smile.campaign.service.campaign_folder.class%
        arguments:
            - @welp_mailchimp.mailchimp_master

    smile.campaign.service.campaigns:
        class: %smile.campaign.service.campaigns.class%
        arguments:
            - @welp_mailchimp.mailchimp_master

    smile.campaign.service.list:
        class: %smile.campaign.service.list.class%
        arguments:
            - @welp_mailchimp.mailchimp_master

    smile.campaign.service.lists:
        class: %smile.campaign.service.lists.class%
        arguments:
            - @welp_mailchimp.mailchimp_master

    # Controllers
    smile.campaign.controller.campaign:
        class: %smile.campaign.controller.campaign.class%
        arguments:
            - %smile.campaign.tabs%
            - @smile.campaign.service.campaigns
            - @smile.campaign.service.campaign
            - @smile.campaign.service.lists
            - @ezrepoforms.action_dispatcher.content_type
            - @ezrepoforms.action_dispatcher.content_type
        parent: ezpublish.controller.base

    smile.campaign.controller.list:
        class: %smile.campaign.controller.list.class%
        arguments:
            - @smile.campaign.service.list
            - @ezrepoforms.action_dispatcher.content_type
        parent: ezpublish.controller.base

    smile.campaign.controller.campaigns:
        class: %smile.campaign.controller.campaigns.class%
        arguments:
            - @smile.campaign.service.campaigns
            - @smile.campaign.service.campaign_folders
        parent: ezpublish.controller.base

    smile.campaign.controller.lists:
        class: %smile.campaign.controller.lists.class%
        arguments:
            - @smile.campaign.service.lists
        parent: ezpublish.controller.base



